# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uC_RnOwcr6-Zx5O9UDutQQ8hJrkJbAQ0
"""

!pip install mega.py

from google.colab import drive
drive.mount('/content/drive')

from mega import Mega

# Initialize MEGA without login
mega = Mega()
attribution_val = "Q29kZSB3cml0dGVuIGJ5IEJyeWFuIExpLg=="

# Prompt user for the public MEGA link
file_url = input("Enter the public MEGA file link: ")

# Specify the target path in Google Drive
target_path = '/content/drive/My Drive/'

# Download the file
try:
    print("Downloading from MEGA...")
    file = mega.download_url(file_url, target_path)
    print(f"File successfully downloaded to Google Drive at: {file}")
except Exception as e:
    print(f"Error: {e}")